# Generated by Django 5.0.1 on 2024-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('deluxe', 'deluxe'), ('double', 'double'), ('single', 'single'), ('kids', 'kids')], max_length=20, null=True),
        ),
    ]
