# Generated by Django 5.0.1 on 2024-02-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Deluxe', 'Deluxe'), ('Double', 'Double'), ('Single', 'Single'), ('Kids', 'Kids')], max_length=20, null=True),
        ),
    ]
